#!/bin/bash
echo  "Updating izing, please wait."
sleep 3s
cd /var/www/html/izing.io
git checkout master
git pull
cd backend
npm install
rm -rf dist
npm run build
npx sequelize db:migrate
#npx sequelize db:seed
pm2 restart all

echo  "Atualizado com Sucesso!"
sleep 3s
